FROM postgres:11.2
#RUN mkdir /docker-entrypoint-initdb.d
#COPY init.sql /docker-entrypoint-initdb.d/
#ADD ./init.sql /docker-entrypoint.initdb.d/init.sql
#RUN cat /docker-entrypoint-initdb.d/init.sql
ENV PGDATA=/data

